name: test
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.vi }} / ${{ matrix.cp }}, ${{ matrix.dl }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-11]
        vi: [neovim, vim]
        cp: [system, copy]
        dl: [git, curl, wget]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: 'stable'
          neovim: ${{ matrix.vi == 'neovim' }}
      - name: Run tests with git
        timeout-minutes: 5
        env:
          JETPACK_DOWNLOAD_METHOD: ${{ matrix.dl }}
          JETPACK_COPY_METHOD: ${{ matrix.cp }}
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: ./vim-themis/bin/themis ./test/test.vim
